### ISSUE TITLE
services are not working properly.

### ISSUE THREAD

**Issue by odidev** [asc-lab/dotnetcore-microservices-poc#57]
@wojteksuwala 

I have successfully deployed microservices on both arm64 and x86_64 platforms, and I am also working on load testing using Locust. But product, pricing, and policy search services are not working properly. 
Initially, when I ran docker-compose it worked fine, but the next time when I ran docker-compose the price of an insurance policy is not visible or calculated after purchase. It only works if all the images created by Docker Compose are removed.
Could you please share your feedback regarding the same?
Also, it would be really helpful if you can confirm that this demo application work only once or if can it be used for load testing.

**UI interface for Product service:**
![image](https://github.com/asc-lab/dotnetcore-microservices-poc/assets/92078754/3972f55e-dd25-458c-839f-b3c9d4dbd0c9)

**Comment by wojteksuwala** [comment]
Unfortunately, I wasn't responsible for the initial dockerization of the app. However, I do not think my teammate's intention was to make it run once only.
I mean, the app should run fine under load testing.
Can you provide some more info - logs, any exceptions details?

**Comment by odidev** [comment]
[@wojteksuwala](https://github.com/wojteksuwala) 

I am trying to deploy microservices by using the `docker-compose -f infra.yml -f app.yml up -d` command on both arm64 and amd64 platforms but I am not able to deploy them properly. I am getting failure in Product-service. 
Previously I commented on an existing [issue](https://github.com/asc-lab/dotnetcore-microservices-poc/issues/47) and at that time I was not able to deploy application, now App is deployed successfully, and the UI is accessible on the browser, but the services are not working properly. 
Please find the below logs and share your feedback regarding the same and let me know if you need any other information from my side. 

 

**product_service_failures:**  [product_service_failure.txt](https://github.com/asc-lab/dotnetcore-microservices-poc/files/11878346/product_service_failure.txt)

**Comment by wojteksuwala** [comment]
The logs fragment you provided does not correspond with the error description from your first entry. In the logs fragment we see there us a problem with contacting eureka server from product service. 
Good news is that I was able to repeat original problem - after first successful calculation of any insurance offer any other failed with HTTP 502. It seems that PolicyService is crushing with Unhandled exception. System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
2023-06-27T19:54:41.184126414Z    at System.Threading.Monitor.Exit(Object obj)
2023-06-27T19:54:41.184131780Z    at PolicyService.Messaging.RabbitMq.Outbox.OutboxSendingService.PushMessages(Object state) in /opt/app/PolicyService/Messaging/RabbitMq/Outbox/OutboxSendingService.cs:line 55
2023-06-27T19:54:41.184135759Z    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
2023-06-27T19:54:41.184140176Z    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2023-06-27T19:54:41.184143928Z    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart().
I will try to look at it this or next weekend or you are more then welcome to create a pull request

**Comment by wojteksuwala** [comment]
Fixed with https://github.com/asc-lab/dotnetcore-microservices-poc/commit/e0468a687feed02e0345eec9ff051f50c715a24b

**Comment by odidev** [comment]
@wojteksuwala  

I have tried with the latest commit, and I am still facing the same as before. But this time the product service worked more than once, and the offer got calculated. But after trying 2-3 times it is not able to calculate the offer as well as policy service is also not running.

**Comment by wojteksuwala** [comment]
Please, check out the logs. If any of the services stop working, there must be a reason. Without exception details and the stack trace, I am unable to help you. I tested the app locally yesterday, created 3 or 4 policies and it seemed working fine. But still, some errors may occur only under load or on slower machines.

**Comment by odidev** [comment]
[@wojteksuwala](https://github.com/wojteksuwala) 
I tried running services on high-configuration machines like AWS c7g.16xlarge but I'm still getting the same failures.  

Please find attached the logs for the offer, product, and policy service containers: 
![image](https://github.com/asc-lab/dotnetcore-microservices-poc/assets/40816837/fe3bbd71-90e4-426f-b247-46f3eb86f497)

**Product_service_logs:** [product-service_container-logs.txt](https://github.com/asc-lab/dotnetcore-microservices-poc/files/11944768/product-service_container-logs.txt) 
**Offer_service_logs:** [pricing-service_container-logs.txt](https://github.com/asc-lab/dotnetcore-microservices-poc/files/11944769/pricing-service_container-logs.txt) 
**Policy_service_logs:** [policy-service-container_logs.txt](https://github.com/asc-lab/dotnetcore-microservices-poc/files/11975155/policy-service-container_logs.txt) 

Below is the complete log for `docker-compose -f infra.yml -f app.yml build –no-cache` and 
`docker-compose -f infra.yml -f app.yml up ` commands. 
 

**Docker-compose_logs:** [docker_compose.txt](https://github.com/asc-lab/dotnetcore-microservices-poc/files/11944776/docker_compose.txt) 

I also tried below-mentioned steps to resolve this failure: 

In the **eureka-server/src/main/resources/application.yml file**, changed 

```
host.docker.internal from hostname: localhost  
```
 After that, added environment value for all the services in both the yml files (infra.yml & app.yml): 
```
environment: 
          - eureka.client.service-url.defaultZone=http://service-registration:8761/eureka  
```

**Note:** I have used these aws ec2 instance (t4g.2xlarge, t4g.large, t4g.2xlarge and c7g.16xlarge) for deployment. 

Likewise, let me know if the deployment of these microservices requires any specific machine type.

**Comment by wojteksuwala** [comment]
From what I see in the log,  order of running services and infra is wrong.
You have to run things like eureka and rabbit before you start microservices.
I am unable to help you with your aws configuration, as I don;t have much hands-on experience with devops on aws.
Services are just regular .net apps, there is nothing special in it (apart from the fact that they have dependencies on infra components like eureka, rabbitmq or databases). You have to coordinate your deployment so rabbitmq, eureka and databases start first. Or you have to configure it to auto restart on such failures.

**Comment by odidev** [comment]
[@wojteksuwala](https://github.com/wojteksuwala) 
As per your suggestion, after starting the infrastructure service before the application services, the issue was resolved and the product, pricing, and policies are working fine.  

However, some search services that are based on elastic search microservices are not running. I changed the elasticsearch images for both platforms to the latest, but the issue persists. 
I have attached the logs for the elastic search container. Could you please share your feedback regarding the same. 

**elasticsearch_container_logs:**  [elasticsearch_container_logs.txt](https://github.com/asc-lab/dotnetcore-microservices-poc/files/12105064/elasticsearch_container_logs.txt)

![image](https://github.com/asc-lab/dotnetcore-microservices-poc/assets/40816837/88d686cb-ac9f-4a75-91c2-e42babdfae28)

**Comment by wojteksuwala** [comment]
The app was not tested with higher versions of elastic. I am currently working on an upgrade.
Not being an expert on elastic cloud deployment I see the following line in the log

max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

Maybe this can be cause of your issue.
I think this is already being mentioned in our readme
